ui = tagList(
  
  navbarPage(
    
    theme = shinytheme("cerulean"),
    
    "LAGOON-MCL",
    
    tabPanel("Results analysis",
             
             sidebarPanel(fileInput("file", "File input:", accept = c("text/tsv", "text/tab-separated-value", "text/plain", ".tsv")),
                          fluidRow(radioButtons("plot_type", "Plot type:", list("Histogram", "Boxplot", "Point")),
                                   conditionalPanel(condition = "input.plot_type == 'Histogram'",
                                                    uiOutput("columnX"),
                                                    uiOutput("clusterSize"),
                                                    sliderInput("sliderHomSc", "Homogeneity score:", 0, 1, value = c(0.0, 1.0)),
                                                    numericInput("sliderBins", "Bins:", min = 1, value = 50, step = 1),
                                                    textInput("titlePlotLabel", "Title plot:", "Distribution homogeneity score"),
                                                    textInput("titleAxisXLabel", "Title axis X", "Homogeneity score"),
                                                    textInput("titleAxisYLabel", "Title axis Y", "Number of cluster"),
                                                    downloadButton("downloadPlotLabeljpg", "Download plot (.jpg)"),
                                                    downloadButton("downloadPlotLabelpdf", "Download plot (.pdf)"),
                                                    downloadButton("downlaodDataframe", "Download data (.tsv)")),
                                   conditionalPanel(condition = "input.plot_type == 'Boxplot'",
                                                    p("In development")),
                                   conditionalPanel(condition = "input.plot_type == 'Point'",
                                                    p("In development"))
                                   )
                          ),
             mainPanel(tabsetPanel(type = "tabs",
                                   tabPanel("Summary",
                                            conditionalPanel(condition = c("input.plot_type == 'Histogram'"),
                                                             h4("Size distribution"),
                                                             plotOutput("histSize"))),
                                   tabPanel("Plot",
                                            conditionalPanel(condition = c("input.plot_type == 'Histogram' && input.Xcol != 'CC_size' && input.Xcol != 'CC'"),
                                                             h4("Homogeneity score distribution"),
                                                             plotOutput("histLabel"))),
                                   tabPanel("Table selection"))
                       )
             ),
    tabPanel("About",
             p("This shiny application lets you interactively explore the 
               various TSV files generated by the LAGOON-MCL pipeline."))
  )
)